environment:
  nodejs_version: "14"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

version: 1.0.{build}
artifacts:
- path: build
  name: build
- path: build\test-win.exe
  name: window build
- path: build\test-linux
  name: linux build
- path: build\test-macos
  name: macos build
build_script:
- ps: >-
    npm install -g pkg-fetch@2.5.8

    npm install -g pkg

    cd Node.js

    npm install

    cd ..

    cd build

    pkg ../Node.js/test.js

    cd ..